#!/bin/bash
f_stock(){
	echo "$nom $cne $moyen" >> ficher.txt
}
f_calcul(){
	while read line;
	do
		nom=$(echo "$line" | cut -d " " -f1)
		cne=$(echo "$line" | cut -d " " -f2)
		val1=$(echo "$line" | cut -d " " -f3)
		val2=$(echo "$line" | cut -d " " -f4)
		moyen=$(( (val1 + val2) / 2 ))
		f_stock "$nom $cne $moyen"
	done < fichnote.txt
}
f_calcul
