#!/bin/bash


check_user(){
	while read line;
	do
		if grep "^$line" /etc/passwd >> /dev/null;
		then
			echo "le compte $line existe";
		else
			echo "le compte $line n'existe pas"
		fi
	done < "$1"
}
if [ -z "$1" ];
then
	echo "no parameter passed"
	exit 1
fi


check_user "$1"
