#!/bin/bash
if [ -z "$1" ];
then
	echo "no parameter passed"
	exit 1
fi
while read line;
do
	login=$(echo "$line" | cut -f1 -d$'\t')
	last_name=$(echo "$line" | cut -f2 -d$'\t')
	first_name=$(echo "$line" | cut -f3 -d$'\t')
done < file.txt

file="$1"
if [ ! -f file ];
then
	echo "file does not exist"
	exit 1
fi
