#!/bin/bash

declare -A mytable

i=0
while read line;
do
    var=1
    for ((j=0; j<=2; j++));
	do
        mytable["$i","$j"]=$(echo "$line" | cut -d ";" -f$var)
        ((var++))
    done
	((i++))
done < fichier.csv

for ((i=0; i<=3; i++))
do
    for ((j=0; j<=2; j++))
    do
        echo -n "${mytable["$i","$j"]} "
    done
    echo
done
