#!/bin/bash

declare -A mytable

mytable[0,0]="Etudiant"
mytable[0,1]="Note1"
mytable[0,2]="Note2"
mytable[0,3]="Note3"
mytable[0,4]="moyen"


while read line;
do
	i=1
	sum=0
	rav1=$(echo "$line" | cut -d " " -f1)
	rav2=$(echo "$line" | cut -d " " -f2)
	rav3=$(echo "$line" | cut -d " " -f3)
	rav4=$(echo "$line" | cut -d " " -f4)
	mytable["$i",0]="$rav1"
	mytable["$i",1]="$rav2"
	mytable["$i",2]="$rav3"
	mytable["$i",3]="$rav4"
	sum=$((rav1 + rav2 + rav3 + rav4))
	average=$((sum / 3))
	mytable["$i",4]="$average"
	let "i += 1"
done < fichnote2.txt

for ((i=0; i<=3; i++))
do
    for ((j=0; j<=4; j++))
    do
        echo -n "${mytable["$i","$j"]} "
    done
    echo
done
