#!/bin/bash

declare -A mytable

i=0
var=1
while read line;
do
    for ((j=0; j<=2; j++));
	do
        mytable["$i","$j"]=$(echo "$line" | cut -d ";" -f$var)
    done

	((i++))
    ((var++))
done < fichier.csv

for ((i=0; i<=3; i++))
do
    for ((j=1; j<=3; j++))
    do
        echo -n "${mytable["$i","$j"]} "
    done
    echo
done
